"""LaTeX tables for E7 (intervals, coverage, harm), from figures/merged_expE7.json."""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "aaai" / "tables"


def write(name, lines):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text("% generated by sim2/make_tables_e7.py; do not edit by hand\n" + "\n".join(lines) + "\n")
    print(f"wrote aaai/tables/{name}.tex")


def pct(x):
    return "--" if x is None or not np.isfinite(x) else f"{100 * x:.0f}"


def num(x, d=4):
    return "--" if x is None or not np.isfinite(x) else f"{x:.{d}f}".replace("-", "$-$")


def tables_e7():
    path = ROOT / "figures/merged_expE7.json"
    if not path.exists():
        return
    d = json.loads(path.read_text())
    A, B = d["A"], d["B"]
    reps = next(iter(A["bootstrap_coverage"].values()))["E3_rollout_pi_vs_policy_contrast"]["replicates"]
    rows = (("Proposed $X$", "E3_rollout_X_vs_policy_contrast", "own"),
            ("Proposed $Y$", "E3_rollout_Y_vs_policy_contrast", "own"),
            ("Proposed $\\pi$", "E3_rollout_pi_vs_policy_contrast", "own"),
            ("Monitor $X$", "naive2_X_vs_marginal_game", "own"),
            ("Monitor $Y|X$", "naive2_Ygx_vs_marginal_game", "own"),
            ("Monitor $Y|X$ vs.\\ policy-contrast $Y$", "naive2_Ygx_vs_policy_contrast_Y", "other"),
            ("Union graph $\\pi$, unclipped", "union3_raw_pi_vs_shapley", "own"),
            ("Union graph $\\pi$, clipped", "union3_clip_pi_vs_shapley", "own"))
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
             "\\caption{Analyst-facing intervals. Share of replicates (\\%) whose 95\\% patient-level bootstrap "
             f"interval ({d['parameters']['boots']} resamples) covers the estimator's own estimand, with the median "
             f"interval width in Brier units, over {reps} independent replicates per scenario ($n=20{{,}}000$ per "
             "environment). One row scores the monitor against the policy-contrast outcome term, the target a "
             "refit decision needs. ``exact'': the term is identically zero when nothing is deployed.}", "\\label{tab:coverage}",
             "\\resizebox{\\columnwidth}{!}{%", "\\begin{tabular}{lcccc}", "\\toprule",
             "Estimator and term & S1 & S2 & S3 & S4\\\\", "\\midrule"]
    for label, key, _ in rows:
        cells = []
        for sc in ("S1", "S2", "S3", "S4"):
            c = A["bootstrap_coverage"][sc][key]
            if c["median_width"] == 0:
                cells.append("exact")          # the term is identically zero without deployment
            else:
                cells.append(f"{pct(c['coverage'])} ({num(c['median_width'], 3)})")
        lines.append(label + " & " + " & ".join(cells) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]
    write("e7_coverage", lines)

    lines = ["\\begin{table}[h]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
             "\\caption{Positivity continuum and sample size. Top: coverage (\\%) of the 95\\% patient-level "
             "bootstrap interval for the policy term, S3 operating point. Bottom: union-graph estimate at "
             "$\\varepsilon=0$ against its target, with the median analyst interval; the interval narrows around a "
             "value of the wrong sign.}", "\\label{tab:positivity-ci}",
             "\\begin{tabular}{lccc}", "\\toprule",
             "$\\varepsilon$ & Union, unclipped & Union, clipped & Proposed\\\\", "\\midrule"]
    for r in B["summary"]:
        cv = r["coverage"]
        lines.append(f"{r['eps']:g} & {pct(cv['union3_raw_pi_vs_shapley']['coverage'])} & "
                     f"{pct(cv['union3_clip_pi_vs_shapley']['coverage'])} & {pct(cv['E3_pi_vs_policy_contrast']['coverage'])}\\\\")
    lines += ["\\midrule", "$n$ & Estimate & Median 95\\% interval & Covers target\\\\", "\\midrule"]
    for r in B["n_scaling"]["summary"]:
        lo, hi = r["analyst_ci95_median"]
        lines.append(f"{r['n']:,}".replace(",", "{,}") + f" & {num(r['union3_raw_pi']['mean'])} & "
                     f"[{num(lo)}, {num(hi)}] & {pct(r['analyst_ci_covers_truth'])}\\%\\\\")
    target = B["n_scaling"]["summary"][0]["truth_shapley_pi"]
    lines += ["\\midrule", f"\\multicolumn{{4}}{{l}}{{Target (oracle Shapley policy term): {num(target)}}}\\\\",
              "\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("e7_positivity", lines)

    D = d["D"]["summary"]
    grid = d["parameters"]["harm_grid"]
    half = max(max(e["mean"] - e["ci95"][0], e["ci95"][1] - e["mean"])
               for r in D if r["theta"] == 2.5 for e in (r["net_averted_pp_by_harm"][str(h)] for h in grid))
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{4pt}",
             "\\caption{Harm sensitivity. Net events averted by the alert policy against standard care "
             "(percentage points) when each extra treatment of a patient whose untreated outcome is 0 costs $h$ "
             f"events; $\\theta = 2.5$, mean over {d['parameters']['reps_d']} independent replicates per cell; "
             f"95\\% bootstrap intervals are within $\\pm{half:.2f}$.}}",
             "\\label{tab:harm}", "\\begin{tabular}{l" + "c" * len(grid) + "}", "\\toprule",
             "Adherence & " + " & ".join(f"$h={h:g}$" for h in grid) + "\\\\", "\\midrule"]
    for r in sorted((r for r in D if r["theta"] == 2.5), key=lambda r: r["p_alert"]):
        cells = []
        for h in grid:
            e = r["net_averted_pp_by_harm"][str(h)]
            cells.append(f"{e['mean']:.2f}")
        lines.append(f"{r['p_alert']:g} & " + " & ".join(cells) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("e7_harm", lines)


if __name__ == "__main__":
    tables_e7()
