"""Write the LaTeX tables that report E-series results, straight from figures/*.json.

Each table is written to aaai/tables/<name>.tex and \\input by the manuscript,
so every number in them is traceable to a JSON in figures/ and the script that
produced it.
"""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "aaai" / "tables"


def load(name):
    path = ROOT / "figures" / name
    return json.loads(path.read_text()) if path.exists() else None


def write(name, lines):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text("% generated by sim2/make_tables.py; do not edit by hand\n" + "\n".join(lines) + "\n")
    print(f"wrote aaai/tables/{name}.tex")


def fmt(v, digits=2, sign=False):
    if v is None or not np.isfinite(v):
        return "--"
    s = f"{v:+.{digits}f}" if sign else f"{v:.{digits}f}"
    return s.replace("-", "$-$") if not sign else s.replace("+", "$+$").replace("-", "$-$")


def ci(entry, digits=2):
    lo, hi = entry["ci95"]
    return f"{fmt(entry['mean'], digits)} [{fmt(lo, digits)}, {fmt(hi, digits)}]"


# ----------------------------------------------------------------------------- E1
def table_e1():
    d = load("merged_expE1.json")
    if d is None:
        return
    rows = (("never", "Never refit"), ("always", "Always refit (naive)"),
            ("exo_proposed", "Refit if exogenous share $>1/2$"),
            ("outcome_proposed", "Refit if outcome share $>1/2$"),
            ("outcome_monitor", "\\quad same, monitor (no action log)"),
            ("refit_untreated", "Reference: refit on $A{=}0$"))
    worst = {w["rule"]: w for w in d["worst_case"] if w["threshold_rule"] == "fixed"}
    half_widths = [max(t["events_averted_pp"]["ci95"][1] - t["events_averted_pp"]["mean"],
                       t["events_averted_pp"]["mean"] - t["events_averted_pp"]["ci95"][0])
                   for t in d["table"] if t["threshold_rule"] == "fixed"]
    reps = d["parameters"]["reps"]
    lines = [
        "\\begin{table}[t]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
        "\\caption{Keep-or-refit rules, fixed alert threshold. Events averted against standard care in "
        "the window after the decision (percentage points), mean over "
        f"{reps} independent replicates per scenario; 95\\% bootstrap intervals are within "
        f"$\\pm{max(half_widths):.2f}$. Percentages give how often a rule refits. Regret is measured "
        "against the better of keeping and naive refitting in each replicate; a negative value beats both.}",
        "\\label{tab:decision}",
        "\\resizebox{\\columnwidth}{!}{%", "\\begin{tabular}{lrrrrrr}", "\\toprule",
        "Rule & S1 & S2 & S3 & S4 & \\multicolumn{2}{c}{Regret}\\\\",
        "& & & & & mean & worst\\\\", "\\midrule"]
    for rule, label in rows:
        cells = []
        for sc in ("S1", "S2", "S3", "S4"):
            e = next(t for t in d["table"] if t["threshold_rule"] == "fixed" and t["scenario"] == sc and t["rule"] == rule)
            cell = fmt(e["events_averted_pp"]["mean"], 1)
            if rule in ("exo_proposed", "outcome_proposed", "outcome_monitor"):
                cell += f" ({100 * e['retrain_fraction']:.0f}\\%)"
            cells.append(cell)
        w = worst[rule]
        lines.append(f"{label} & " + " & ".join(cells) + f" & {fmt(w['mean_regret_pp'], 1)} & {fmt(w['max_mean_regret_pp'], 1)}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]
    write("e1_decision", lines)

    # appendix: rate-held threshold and harm sensitivity
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
             "\\caption{Keep-or-refit rules under the rate-held threshold (events averted, pp) and harm sensitivity under the fixed "
             "threshold: net events averted when each extra treatment of a patient whose untreated outcome is 0 "
             "costs $h$ events.}", "\\label{tab:decision-app}",
             "\\begin{tabular}{llrrrr}", "\\toprule", "Threshold & Rule & S1 & S2 & S3 & S4\\\\", "\\midrule"]
    for rule, label in rows:
        cells = [fmt(next(t for t in d["table"] if t["threshold_rule"] == "rate" and t["scenario"] == sc
                          and t["rule"] == rule)["events_averted_pp"]["mean"], 2) for sc in ("S1", "S2", "S3", "S4")]
        lines.append(f"rate-held & {label} & " + " & ".join(cells) + "\\\\")
    lines.append("\\midrule")
    for h in (0.1, 0.2):
        for rule, label in rows:
            cells = [fmt(next(x for x in d["harm_sensitivity"] if x["threshold_rule"] == "fixed" and x["scenario"] == sc
                              and x["rule"] == rule and x["harm_per_unnecessary_treatment"] == h)
                         ["net_events_averted_pp"]["mean"], 1) for sc in ("S1", "S2", "S3", "S4")]
            lines.append(f"fixed, $h={h:g}$ & {label} & " + " & ".join(cells) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("e1_decision_appendix", lines)


# ----------------------------------------------------------------------------- E3
def table_e3():
    d = load("merged_expH.json")
    if d is None:
        return
    arms = (("keep", "Keep original score"), ("naive", "Naive refit"), ("unalerted", "Refit below threshold"),
            ("conditional_main", "Condition on $A$, main effects"), ("untreated", "Refit on $A{=}0$"),
            ("conditional_interactions", "Condition on $A$ with $X{\\times}A$"),
            ("untreated_ipw", "Refit on $A{=}0$, weighted"),
            ("untreated_ipw_est", "\\quad same, estimated weights"))
    settings = ("fixed_k0", "fixed_k2", "fixed_nl", "rate_k0", "rate_k2", "rate_nl")
    last = d["parameters"]["rounds"]
    lines = ["\\begin{table*}[t]", "\\centering\\scriptsize",
             f"\\caption{{Update rules after deployment (Experiment C), events averted against standard care at round {last} "
             f"(percentage points), mean and 95\\% bootstrap interval over {d['parameters']['seeds']} independent seeds "
             "per column. ``Weighted'' uses $1/P(A{=}0\\mid X)$ from the logged alert rule and response "
             "probabilities; ``estimated weights'' replaces them with a logistic regression of $A$ on $X$, the alert "
             "and their interaction. Last row: mean score minus mean untreated risk for naive refitting.}",
             "\\label{tab:retrain-app}",
             "\\begin{tabular}{lcccccc}", "\\toprule",
             " & \\multicolumn{3}{c}{Fixed threshold} & \\multicolumn{3}{c}{Rate-held threshold}\\\\",
             "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
             "Rule & $\\kappa=0$ & $\\kappa=2$ & misspecified & $\\kappa=0$ & $\\kappa=2$ & misspecified\\\\", "\\midrule"]
    def cell(setting, arm, key="events_averted_pp", digits=2):
        return next(e for e in d["summary"] if e["setting"] == setting and e["arm"] == arm and e["round"] == last)[key]
    for arm, label in arms:
        lines.append(label + " & " + " & ".join(ci(cell(s, arm), 2) for s in settings) + "\\\\")
    lines.append("\\midrule")
    lines.append("Naive refit, calibration & " + " & ".join(fmt(cell(s, "naive", "calibration_in_large")["mean"], 3, sign=True)
                                                           for s in settings) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    write("e3_retraining", lines)


# ----------------------------------------------------------------------------- E4
def table_e4():
    d = load("merged_expAB_robustness.json")
    if d is None:
        return
    from common import bootstrap_mean_ci
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize",
             "\\caption{S3 attribution and $\\varepsilon=0$ bias with more covariates and a misspecified outcome, Brier units. Estimates are means over "
             f"{d['parameters']['seeds_per_row']} independent seeds with 95\\% bootstrap intervals. The union-graph bias at "
             "$n=" + f"{d['parameters']['n_scaling'][-1]:,}".replace(",", "{,}") + "$ is relative to its oracle Shapley target.}",
             "\\label{tab:robustness}", "\\resizebox{\\columnwidth}{!}{%", "\\begin{tabular}{lrrrr}", "\\toprule",
             "Setting & True $\\Delta R$ & Monitor $Y|X$ & Proposed $\\pi$ & Union bias\\\\", "\\midrule"]
    for st in d["settings"]:
        s3 = next(r for r in st["A"] if r["scenario"] == "S3")
        naive = [r["naive2_est"]["Ygx"] for r in s3["runs"]]
        prop = [r["E3_rollout"]["pi"] for r in s3["runs"]]
        big = st["n_scaling_eps_zero"][-1]
        bias = np.array(big["runs"]) - big["truth_shapley_pi"]
        def c(v):
            lo, hi = bootstrap_mean_ci(v)
            return f"{np.mean(v):.4f} [{lo:.4f}, {hi:.4f}]".replace("-", "$-$")
        label = f"$d={st['d']}$, {'nonlinear' if st['nonlinear_outcome'] else 'linear'}"
        lines.append(f"{label} & {s3['truth_policy_contrast']['dR']:.4f} & {c(naive)} & {c(prop)} & {c(bias)}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]
    write("e4_robustness", lines)


# ----------------------------------------------------------------------------- E5
def table_e5():
    d = load("merged_expG2.json")
    if d is None:
        return
    names = {"random_order_common_trend": "Random, common", "random_order_site_trend": "Random, site-specific",
             "correlated_order_common_trend": "Linked, common", "correlated_order_site_trend": "Linked, site-specific"}
    cols = (("retro", "Retro."), ("x_endogenous_mean", "Induced"), ("x_exogenous_mean", "Exog."),
            ("x_endogenous_loss", "Induced"), ("x_exogenous_loss", "Exog."),
            ("x_endogenous_loss_did", "Induced"), ("x_exogenous_loss_did", "Exog."))
    lines = ["\\begin{table*}[t]", "\\centering\\scriptsize",
             "\\caption{Persistent-site stepped wedge: bias as a percentage of the true value, with 95\\% bootstrap "
             f"interval, over {d['parameters']['seeds_per_row']} independent seeds per row. Rollout order is random or linked "
             "to the site characteristic; covariate trends are common or site specific. Retrospective term: crossover "
             "difference in differences. $X$ split in the covariate mean, and on the Brier scale by the plug-in and the "
             "DiD-anchored estimators.}",
             "\\label{tab:sites}", "\\resizebox{\\textwidth}{!}{%", "\\begin{tabular}{lccccccc}", "\\toprule",
             "Rollout order, trend & Retrospective & \\multicolumn{2}{c}{$X$ mean split} & "
             "\\multicolumn{2}{c}{Brier $X$ split, plug-in} & \\multicolumn{2}{c}{Brier $X$ split, DiD-anchored}\\\\",
             "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
             " & " + " & ".join(c[1] for c in cols) + "\\\\", "\\midrule"]
    for row in d["rows"]:
        s = row["summary"]
        cells = []
        for key, _ in cols:
            v = s[key]
            lo, hi = (100 * np.array(v["bias_ci95"]) / v["truth_mean"])
            lo, hi = min(lo, hi), max(lo, hi)
            cells.append(f"{100 * v['relative_bias']:+.1f} [{lo:+.1f}, {hi:+.1f}]".replace("-", "$-$").replace("+", "$+$"))
        lines.append(names[row["setting"]] + " & " + " & ".join(cells) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table*}"]
    write("e5_sites", lines)


# ----------------------------------------------------------------------------- prevalence
def table_prevalence():
    d = load("merged_expP.json")
    if d is None:
        return
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
             "\\caption{Sign of the S3 change across outcome prevalence, alert rate held at "
             f"{100 * d['parameters']['alert_rate']:.0f}\\%. Oracle values (expected Brier scores, mean over "
             f"{d['parameters']['blocks']} independent blocks of " + f"{d['parameters']['n']:,}".replace(",", "{,}") +
             " patients; Monte Carlo SE below $10^{-4}$). The monitor books the whole change to $P(Y\\mid X)$ at "
             "every prevalence; only its sign changes.}",
             "\\label{tab:prevalence}", "\\resizebox{\\columnwidth}{!}{%", "\\begin{tabular}{rrrrrr}", "\\toprule",
             "Event rate & Mean score, alerted & $\\Delta R$ & Policy (Shapley) & Monitor $Y|X$ & AUROC before, after\\\\",
             "\\midrule"]
    for r in d["rows"]:
        lines.append(f"{r['event_rate_untreated']['mean']:.3f} & {r['mean_score_alerted']['mean']:.2f} & "
                     f"{fmt(r['dR']['mean'], 4, sign=True)} & {fmt(r['policy_shapley']['mean'], 4, sign=True)} & "
                     f"{fmt(r['monitor_Ygx']['mean'], 4, sign=True)} & {r['auroc_before']['mean']:.3f}, "
                     f"{r['auroc_after']['mean']:.3f}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]
    write("prevalence", lines)


def table_prevalence_estimators():
    """Experiment A (E7 machinery) and E1 at a realistic event rate (merged_expE7_prev.json, merged_expE1_prev.json)."""
    a, e1 = load("merged_expE7_prev.json"), load("merged_expE1_prev.json")
    if a is None or e1 is None:
        return
    A, op = a["A"], a["A"]["operating_point"]
    lines = ["\\begin{table*}[t]", "\\centering\\scriptsize",
             f"\\caption{{Experiment A and the keep-or-refit rules at an untreated event rate of {100 * op['event_rate_untreated']:.1f}\\% "
             f"($b_0 = {op['b0']:g}$, alert rate {100 * e1['parameters']['alert_rate']:.0f}\\%), $n = 20{{,}}000$ per "
             "environment. Top: attribution of the Brier-score change, oracle targets and estimator means with 95\\% "
             f"bootstrap intervals over {a['parameters']['reps_a']} replicates, and coverage (\\%) of the 95\\% "
             "patient-level bootstrap interval: the proposed policy term against its target, and the monitor's "
             "$P(Y\\mid X)$ term against the policy-contrast outcome term. The union-graph estimator targets the "
             "policy player's Shapley value, "
             f"{fmt(A['references']['S3']['shapley_pi']['value'], 4, sign=True)} in S3 and "
             f"{fmt(A['references']['S4']['shapley_pi']['value'], 4, sign=True)} in S4. Bottom: keep-or-refit rules, events averted after the "
             f"keep-or-refit decision (percentage points, fixed threshold, {e1['parameters']['reps']} replicates per "
             "scenario), with how often a rule refits.}", "\\label{tab:prevalence-est}",
             "\\resizebox{\\textwidth}{!}{%", "\\begin{tabular}{lcccccc}", "\\toprule",
             "Scenario & $\\Delta R$ & Policy contrast & Monitor $P(Y\\mid X)$ & Proposed $\\pi$ & Union graph $\\pi$ & "
             "Coverage: proposed, monitor\\\\", "\\midrule"]
    for sc in ("S3", "S4"):
        ref, summ, cov = A["references"][sc], A["summary"][sc], A["bootstrap_coverage"][sc]
        lines.append(f"{sc} & {fmt(ref['dR']['value'], 4, sign=True)} & {fmt(ref['pc_pi']['value'], 4, sign=True)} & "
                     f"{brier_ci(summ['naive2_est_Ygx'], 4)} & {brier_ci(summ['E3_rollout_pi'], 4)} & "
                     f"{brier_ci(summ['union3_raw_pi'], 4)} & "
                     f"{100 * cov['E3_rollout_pi_vs_policy_contrast']['coverage']:.0f}, "
                     f"{100 * cov['naive2_Ygx_vs_policy_contrast_Y']['coverage']:.0f}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "", "\\vspace{0.6em}", "\\begin{tabular}{lcccc}", "\\toprule",
              "Rule & S1 & S2 & S3 & S4\\\\", "\\midrule"]
    t = {(x["scenario"], x["rule"]): x for x in e1["table"] if x["threshold_rule"] == "fixed"}
    for rule, label in (("never", "Never refit"), ("always", "Always refit (naive)"),
                        ("exo_proposed", "Refit if exogenous share $>1/2$"),
                        ("outcome_proposed", "Refit if outcome share $>1/2$"),
                        ("outcome_monitor", "\\quad same, monitor (no action log)"),
                        ("refit_untreated", "Reference: refit on $A{=}0$")):
        cells = []
        for sc in ("S1", "S2", "S3", "S4"):
            e = t[(sc, rule)]
            cell = fmt(e["events_averted_pp"]["mean"], 2)
            if rule in ("exo_proposed", "outcome_proposed", "outcome_monitor"):
                cell += f" ({100 * e['retrain_fraction']:.0f}\\%)"
            cells.append(cell)
        lines.append(f"{label} & " + " & ".join(cells) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    write("prevalence_estimators", lines)


# ----------------------------------------------------------------------------- E6
E6_TAGS =(("rrr25", "Action prevents the event w.p.\\ 0.25"), ("rrr75", "Action prevents the event w.p.\\ 0.75"),
           ("alert05", "Alert rate 5\\%"), ("alert20", "Alert rate 20\\%"),
           ("admyear", "Periods by admission year"), ("covid", "Late period 2020--2022"))


def years(groups):
    """'2008 - 2010', '2011 - 2013' -> '2008--2013'."""
    import re
    ys = [int(y) for g in groups for y in re.findall(r"\d{4}", g)]
    return f"{min(ys)}--{max(ys)}"


def ci_or_value(entry, digits=2):
    """Mean and interval, or the mean alone when there is no Monte Carlo spread."""
    lo, hi = entry["ci95"]
    return fmt(entry["mean"], digits) if hi - lo < 0.5 * 10 ** -digits else ci(entry, digits)


def thousands(n):
    return f"{n:,}".replace(",", "{,}")


def brier_ci(entry, digits):
    lo, hi = entry["ci95"]
    if entry["mean"] == lo == hi == 0:
        return "0"                     # identically zero (no deployment)
    return f"{fmt(entry['mean'], digits, sign=True)} [{fmt(lo, digits, sign=True)}, {fmt(hi, digits, sign=True)}]"


def table_e6(d=None):
    """Appendix table for the main E6 run: cohort in the caption, attribution and update rules in the body."""
    d = d or load("merged_expE6.json")
    if d is None:
        return
    from e6_report import brier_digits, final_round
    k = brier_digits(d)
    c, p, A = d["cohort"], d["parameters"], d["A"]
    S, T = A["summary"], A["truth"]
    names = ("deploy_only", "drift_only", "drift_and_deploy")
    lines = ["\\begin{table*}[t]", "\\centering\\scriptsize",
             f"\\caption{{Semi-synthetic MIMIC-IV. Cohort: {thousands(c['admissions'])} ward admissions of "
             f"{thousands(c['patients'])} adult patients; event rate {100 * c['event_rate_early']:.1f}\\% in {years(p['early'])} and "
             f"{100 * c['event_rate_late']:.1f}\\% in {years(p['late'])}; score AUROC "
             f"{c['score_auroc_early_heldout']:.3f} on held-out early patients and {c['score_auroc_late']:.3f} in the "
             f"late period; alert rate {100 * c['alert_rate_late']:.1f}\\% in the late period at the fixed threshold. "
             f"Top: attribution of the Brier-score change, mean over {p['reps_a']} replicates with 95\\% bootstrap "
             "intervals; targets are exact for the cohort in expectation over the simulated components. Bottom: "
             f"events averted against historical care at round {p['rounds']} (percentage points), {p['reps_c']} "
             "replicates.}", "\\label{tab:mimic}", "\\begin{tabular}{lccc}",
             "\\toprule", " & Deployment only & Drift only & Drift and deployment\\\\", "\\midrule"]

    def row(label, cell):
        lines.append(label + " & " + " & ".join(cell(n) for n in names) + "\\\\")
    row("Policy contrast (target)", lambda n: fmt(T[n]["pi"], k, sign=True) if T[n]["pi"] != 0 else "0")
    row("Proposed, policy term", lambda n: brier_ci(S[n]["proposed_pi"], k))
    row("Union graph, oracle weights", lambda n: brier_ci(S[n]["union_pi"], k) if "union_pi" in S[n] else "--")
    row("Monitor, $P(Y\\mid X)$", lambda n: brier_ci(S[n]["monitor_Ygx"], k))
    row("Exogenous change (target)", lambda n: fmt(T[n]["exogenous"], k, sign=True) if T[n]["exogenous"] != 0 else "0")
    row("Proposed, exogenous terms", lambda n: brier_ci(S[n]["proposed_exogenous"], k))
    row("Observed change in Brier score", lambda n: fmt(S[n]["dR_observed"]["mean"], k, sign=True))
    row("Observed change in AUROC", lambda n: fmt(S[n]["auroc_change_observed"]["mean"], 3, sign=True))
    lines += ["\\midrule", f"Update rule, round {p['rounds']} & Fixed threshold & Rate-held threshold & \\\\", "\\midrule"]
    fixed, rate = final_round(d, "fixed"), final_round(d, "rate")
    for arm, label in (("keep", "Keep"), ("naive", "Naive refit"), ("untreated", "Refit on $A{=}0$"),
                       ("untreated_ipw", "Refit on $A{=}0$, weighted")):
        lines.append(f"{label} & {ci_or_value(fixed[arm]['events_averted_pp'])} & "
                     f"{ci_or_value(rate[arm]['events_averted_pp'])} & \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    write("e6_mimic", lines)


def table_e6_sensitivity(runs=None):
    """Tagged E6 runs (merged_expE6_<tag>.json) against the main run, deployment-only scenario and update rules."""
    main = load("merged_expE6.json") if runs is None else runs.get("main")
    runs = runs or {tag: load(f"merged_expE6_{tag}.json") for tag, _ in E6_TAGS}
    rows = [("main", "Main analysis", main)] + [(t, label, runs.get(t)) for t, label in E6_TAGS]
    rows = [r for r in rows if r[2] is not None]
    if len(rows) < 2:
        return
    from e6_report import brier_digits, final_round
    k = min(brier_digits(d) for _, _, d in rows)
    lines = ["\\begin{table*}[t]", "\\centering\\scriptsize",
             "\\caption{Semi-synthetic MIMIC-IV, sensitivity runs. Deployment-only attribution (policy contrast, its randomised-arm estimate and "
             "the monitor's $P(Y\\mid X)$ term, Brier units) and events averted at the last round under the fixed "
             "threshold (percentage points). Means with 95\\% bootstrap intervals over replicates; the main analysis "
             "uses an alert rate of 10\\%, an action that prevents the event with probability 0.5 and periods by "
             "anchor year group.}", "\\label{tab:mimic-sens}", "\\begin{tabular}{lccccc}", "\\toprule",
             "Setting & Policy contrast & Proposed $\\pi$ & Monitor $P(Y\\mid X)$ & Keep & Naive refit\\\\", "\\midrule"]
    for _, label, d in rows:
        S, T, r8 = d["A"]["summary"]["deploy_only"], d["A"]["truth"]["deploy_only"], final_round(d)
        lines.append(f"{label} & {fmt(T['pi'], k, sign=True)} & {brier_ci(S['proposed_pi'], k)} & "
                     f"{brier_ci(S['monitor_Ygx'], k)} & {fmt(r8['keep']['events_averted_pp']['mean'], 2)} & "
                     f"{ci_or_value(r8['naive']['events_averted_pp'])}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    write("e6_sensitivity", lines)


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    table_e1()
    table_e3()
    table_e4()
    table_e5()
    table_prevalence()
    table_prevalence_estimators()
    table_e6()
    table_e6_sensitivity()
    try:
        from make_tables_e7 import tables_e7
        tables_e7()
    except ImportError:
        pass
