"""Write the LaTeX tables that report E-series results, straight from figures/*.json.

Each table is written to aaai/tables/<name>.tex and \\input by the manuscript,
so every number in them is traceable to a JSON in figures/ and the script that
produced it.
"""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "aaai" / "tables"


def load(name):
    path = ROOT / "figures" / name
    return json.loads(path.read_text()) if path.exists() else None


def write(name, lines):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text("% generated by sim2/make_tables.py; do not edit by hand\n" + "\n".join(lines) + "\n")
    print(f"wrote aaai/tables/{name}.tex")


def fmt(v, digits=2, sign=False):
    if v is None or not np.isfinite(v):
        return "--"
    s = f"{v:+.{digits}f}" if sign else f"{v:.{digits}f}"
    return s.replace("-", "$-$") if not sign else s.replace("+", "$+$").replace("-", "$-$")


def ci(entry, digits=2):
    lo, hi = entry["ci95"]
    return f"{fmt(entry['mean'], digits)} [{fmt(lo, digits)}, {fmt(hi, digits)}]"


# ----------------------------------------------------------------------------- E1
def table_e1():
    d = load("merged_expE1.json")
    if d is None:
        return
    rows = (("never", "Never refit"), ("always", "Always refit (naive)"),
            ("exo_proposed", "Refit if exogenous share $>1/2$"),
            ("outcome_proposed", "Refit if outcome share $>1/2$"),
            ("outcome_monitor", "\\quad same, monitor (no action log)"),
            ("refit_untreated", "Reference: refit on $A{=}0$"))
    worst = {w["rule"]: w for w in d["worst_case"] if w["threshold_rule"] == "fixed"}
    half_widths = [max(t["events_averted_pp"]["ci95"][1] - t["events_averted_pp"]["mean"],
                       t["events_averted_pp"]["mean"] - t["events_averted_pp"]["ci95"][0])
                   for t in d["table"] if t["threshold_rule"] == "fixed"]
    reps = d["parameters"]["reps"]
    lines = [
        "\\begin{table}[t]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
        "\\caption{Keep-or-refit rules (E1), fixed alert threshold. Events averted against standard care in "
        "the window after the decision (percentage points), mean over "
        f"{reps} independent replicates per scenario; 95\\% bootstrap intervals are within "
        f"$\\pm{max(half_widths):.2f}$. Percentages give how often a rule refits. Regret is measured "
        "against the better of keeping and naive refitting in each replicate; a negative value beats both.}",
        "\\label{tab:decision}",
        "\\resizebox{\\columnwidth}{!}{%", "\\begin{tabular}{lrrrrrr}", "\\toprule",
        "Rule & S1 & S2 & S3 & S4 & \\multicolumn{2}{c}{Regret}\\\\",
        "& & & & & mean & worst\\\\", "\\midrule"]
    for rule, label in rows:
        cells = []
        for sc in ("S1", "S2", "S3", "S4"):
            e = next(t for t in d["table"] if t["threshold_rule"] == "fixed" and t["scenario"] == sc and t["rule"] == rule)
            cell = fmt(e["events_averted_pp"]["mean"], 1)
            if rule in ("exo_proposed", "outcome_proposed", "outcome_monitor"):
                cell += f" ({100 * e['retrain_fraction']:.0f}\\%)"
            cells.append(cell)
        w = worst[rule]
        lines.append(f"{label} & " + " & ".join(cells) + f" & {fmt(w['mean_regret_pp'], 1)} & {fmt(w['max_mean_regret_pp'], 1)}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]
    write("e1_decision", lines)

    # appendix: rate-held threshold and harm sensitivity
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
             "\\caption{E1 under the rate-held threshold (events averted, pp) and harm sensitivity under the fixed "
             "threshold: net events averted when each extra treatment of a patient whose untreated outcome is 0 "
             "costs $h$ events.}", "\\label{tab:decision-app}",
             "\\begin{tabular}{llrrrr}", "\\toprule", "Threshold & Rule & S1 & S2 & S3 & S4\\\\", "\\midrule"]
    for rule, label in rows:
        cells = [fmt(next(t for t in d["table"] if t["threshold_rule"] == "rate" and t["scenario"] == sc
                          and t["rule"] == rule)["events_averted_pp"]["mean"], 2) for sc in ("S1", "S2", "S3", "S4")]
        lines.append(f"rate-held & {label} & " + " & ".join(cells) + "\\\\")
    lines.append("\\midrule")
    for h in (0.1, 0.2):
        for rule, label in rows:
            cells = [fmt(next(x for x in d["harm_sensitivity"] if x["threshold_rule"] == "fixed" and x["scenario"] == sc
                              and x["rule"] == rule and x["harm_per_unnecessary_treatment"] == h)
                         ["net_events_averted_pp"]["mean"], 1) for sc in ("S1", "S2", "S3", "S4")]
            lines.append(f"fixed, $h={h:g}$ & {label} & " + " & ".join(cells) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("e1_decision_appendix", lines)


# ----------------------------------------------------------------------------- E3
def table_e3():
    d = load("merged_expH.json")
    if d is None:
        return
    arms = (("keep", "Keep original score"), ("naive", "Naive refit"), ("unalerted", "Refit below threshold"),
            ("conditional_main", "Condition on $A$, main effects"), ("untreated", "Refit on $A{=}0$"),
            ("conditional_interactions", "Condition on $A$ with $X{\\times}A$"),
            ("untreated_ipw", "Refit on $A{=}0$, weighted"))
    settings = ("fixed_k0", "fixed_k2", "fixed_nl", "rate_k0", "rate_k2", "rate_nl")
    last = d["parameters"]["rounds"]
    lines = ["\\begin{table*}[t]", "\\centering\\scriptsize",
             f"\\caption{{Update rules after deployment (E3), events averted against standard care at round {last} "
             f"(percentage points), mean and 95\\% bootstrap interval over {d['parameters']['seeds']} independent seeds "
             "per column. ``Weighted'' uses $1/P(A{=}0\\mid X)$ from the logged alert rule and response "
             "probabilities. Last row: mean score minus mean untreated risk for naive refitting.}",
             "\\label{tab:retrain-app}",
             "\\begin{tabular}{lcccccc}", "\\toprule",
             " & \\multicolumn{3}{c}{Fixed threshold} & \\multicolumn{3}{c}{Rate-held threshold}\\\\",
             "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
             "Rule & $\\kappa=0$ & $\\kappa=2$ & misspecified & $\\kappa=0$ & $\\kappa=2$ & misspecified\\\\", "\\midrule"]
    def cell(setting, arm, key="events_averted_pp", digits=2):
        return next(e for e in d["summary"] if e["setting"] == setting and e["arm"] == arm and e["round"] == last)[key]
    for arm, label in arms:
        lines.append(label + " & " + " & ".join(ci(cell(s, arm), 2) for s in settings) + "\\\\")
    lines.append("\\midrule")
    lines.append("Naive refit, calibration & " + " & ".join(fmt(cell(s, "naive", "calibration_in_large")["mean"], 3, sign=True)
                                                           for s in settings) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    write("e3_retraining", lines)


# ----------------------------------------------------------------------------- E4
def table_e4():
    d = load("merged_expAB_robustness.json")
    if d is None:
        return
    from common import bootstrap_mean_ci
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize",
             "\\caption{S3 attribution and $\\varepsilon=0$ bias (E4), Brier units. Estimates are means over "
             f"{d['parameters']['seeds_per_row']} independent seeds with 95\\% bootstrap intervals. The union-graph bias at "
             "$n=" + f"{d['parameters']['n_scaling'][-1]:,}".replace(",", "{,}") + "$ is relative to its oracle Shapley target.}",
             "\\label{tab:robustness}", "\\resizebox{\\columnwidth}{!}{%", "\\begin{tabular}{lrrrr}", "\\toprule",
             "Setting & True $\\Delta R$ & Monitor $Y|X$ & Proposed $\\pi$ & Union bias\\\\", "\\midrule"]
    for st in d["settings"]:
        s3 = next(r for r in st["A"] if r["scenario"] == "S3")
        naive = [r["naive2_est"]["Ygx"] for r in s3["runs"]]
        prop = [r["E3_rollout"]["pi"] for r in s3["runs"]]
        big = st["n_scaling_eps_zero"][-1]
        bias = np.array(big["runs"]) - big["truth_shapley_pi"]
        def c(v):
            lo, hi = bootstrap_mean_ci(v)
            return f"{np.mean(v):.4f} [{lo:.4f}, {hi:.4f}]".replace("-", "$-$")
        label = f"$d={st['d']}$, {'nonlinear' if st['nonlinear_outcome'] else 'linear'}"
        lines.append(f"{label} & {s3['truth_policy_contrast']['dR']:.4f} & {c(naive)} & {c(prop)} & {c(bias)}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]
    write("e4_robustness", lines)


# ----------------------------------------------------------------------------- E5
def table_e5():
    d = load("merged_expG2.json")
    if d is None:
        return
    names = {"random_order_common_trend": "Random, common", "random_order_site_trend": "Random, site-specific",
             "correlated_order_common_trend": "Linked, common", "correlated_order_site_trend": "Linked, site-specific"}
    cols = (("retro", "Retro."), ("x_endogenous_mean", "Induced"), ("x_exogenous_mean", "Exog."),
            ("x_endogenous_loss", "Induced"), ("x_exogenous_loss", "Exog."),
            ("x_endogenous_loss_did", "Induced"), ("x_exogenous_loss_did", "Exog."))
    lines = ["\\begin{table*}[t]", "\\centering\\scriptsize",
             "\\caption{Persistent-site stepped wedge (E5): bias as a percentage of the true value, with 95\\% bootstrap "
             f"interval, over {d['parameters']['seeds_per_row']} independent seeds per row. Rollout order is random or linked "
             "to the site characteristic; covariate trends are common or site specific. Retrospective term: crossover "
             "difference in differences. $X$ split in the covariate mean, and on the Brier scale by the plug-in and the "
             "DiD-anchored estimators.}",
             "\\label{tab:sites}", "\\resizebox{\\textwidth}{!}{%", "\\begin{tabular}{lccccccc}", "\\toprule",
             "Rollout order, trend & Retrospective & \\multicolumn{2}{c}{$X$ mean split} & "
             "\\multicolumn{2}{c}{Brier $X$ split, plug-in} & \\multicolumn{2}{c}{Brier $X$ split, DiD-anchored}\\\\",
             "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
             " & " + " & ".join(c[1] for c in cols) + "\\\\", "\\midrule"]
    for row in d["rows"]:
        s = row["summary"]
        cells = []
        for key, _ in cols:
            v = s[key]
            lo, hi = (100 * np.array(v["bias_ci95"]) / v["truth_mean"])
            lo, hi = min(lo, hi), max(lo, hi)
            cells.append(f"{100 * v['relative_bias']:+.1f} [{lo:+.1f}, {hi:+.1f}]".replace("-", "$-$").replace("+", "$+$"))
        lines.append(names[row["setting"]] + " & " + " & ".join(cells) + "\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table*}"]
    write("e5_sites", lines)


# ----------------------------------------------------------------------------- prevalence
def table_prevalence():
    d = load("merged_expP.json")
    if d is None:
        return
    lines = ["\\begin{table}[h]", "\\centering\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
             "\\caption{Sign of the S3 change across outcome prevalence, alert rate held at "
             f"{100 * d['parameters']['alert_rate']:.0f}\\%. Oracle values (expected Brier scores, mean over "
             f"{d['parameters']['blocks']} independent blocks of " + f"{d['parameters']['n']:,}".replace(",", "{,}") +
             " patients; Monte Carlo SE below $10^{-4}$). The monitor books the whole change to $P(Y\\mid X)$ at "
             "every prevalence; only its sign changes.}",
             "\\label{tab:prevalence}", "\\resizebox{\\columnwidth}{!}{%", "\\begin{tabular}{rrrrrr}", "\\toprule",
             "Event rate & Mean score, alerted & $\\Delta R$ & Policy (Shapley) & Monitor $Y|X$ & AUROC before, after\\\\",
             "\\midrule"]
    for r in d["rows"]:
        lines.append(f"{r['event_rate_untreated']['mean']:.3f} & {r['mean_score_alerted']['mean']:.2f} & "
                     f"{fmt(r['dR']['mean'], 4, sign=True)} & {fmt(r['policy_shapley']['mean'], 4, sign=True)} & "
                     f"{fmt(r['monitor_Ygx']['mean'], 4, sign=True)} & {r['auroc_before']['mean']:.3f}, "
                     f"{r['auroc_after']['mean']:.3f}\\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]
    write("prevalence", lines)


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    table_e1()
    table_e3()
    table_e4()
    table_e5()
    table_prevalence()
    try:
        from make_tables_e7 import tables_e7
        tables_e7()
    except ImportError:
        pass
